font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

font_size 11.0

# Background
#background #000000
background_opacity 0.85
dynamic_background_opacity yes

# Optional: remove ugly padding feel
window_padding_width 10

# Optional: smoother visuals
enable_audio_bell no

# cursor trail
cursor_trail 1


enable_image_protocol yes
